[package]
name = "lune-roblox"
version = "0.1.4"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/lune-org/lune"
description = "Roblox library for Lune"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
mlua = { version = "0.9.9", features = ["luau"] }

glam = "0.27"
rand = "0.8"
thiserror = "1.0"
once_cell = "1.17"

rbx_binary = { git = "https://github.com/UpliftGames/rbx-dom.git", rev = "66e21b397f6e064d86fa6c8d530ce541864b1d2e" }
rbx_dom_weak = { git = "https://github.com/UpliftGames/rbx-dom.git", rev = "66e21b397f6e064d86fa6c8d530ce541864b1d2e" }
rbx_reflection = { git = "https://github.com/UpliftGames/rbx-dom.git", rev = "66e21b397f6e064d86fa6c8d530ce541864b1d2e" }
rbx_reflection_database = { git = "https://github.com/UpliftGames/rbx-dom.git", rev = "66e21b397f6e064d86fa6c8d530ce541864b1d2e" }
rbx_xml = { git = "https://github.com/UpliftGames/rbx-dom.git", rev = "66e21b397f6e064d86fa6c8d530ce541864b1d2e" }

lune-utils = { version = "0.1.3", path = "../lune-utils" }
